"use client";

import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { motion } from "framer-motion";
import { Check, Copy, ExternalLink, Share2 } from "lucide-react";

interface PublicLinkDisplayProps {
  contractId: string;
  onBack: () => void;
  onFinish: () => void;
}

const PublicLinkDisplay: React.FC<PublicLinkDisplayProps> = ({
  contractId,
  onBack,
  onFinish,
}) => {
  const [copied, setCopied] = useState(false);

  // In a real app, this would be generated by the backend
  const publicLink = `${window.location.origin}/contratos/preencher/${contractId}`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(publicLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleViewPreview = () => {
    window.open(publicLink, "_blank");
  };

  return (
    <div className="space-y-6 py-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
      >
        <Card>
          <CardContent className="pt-6">
            <div className="flex flex-col items-center text-center space-y-4 mb-8">
              <div className="bg-primary/10 p-4 rounded-full">
                <Share2 className="h-8 w-8 text-primary" />
              </div>
              <h3 className="text-xl font-medium">
                Seu contrato está pronto para preenchimento
              </h3>
              <p className="text-muted-foreground max-w-md">
                Copie o link abaixo e envie para o responsável preencher os
                dados. O link é válido por 7 dias.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <Input
                  value={publicLink}
                  readOnly
                  className="font-mono text-sm"
                />
                <Button
                  variant="outline"
                  size="icon"
                  onClick={handleCopyLink}
                  className="flex-shrink-0"
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-green-500" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </Button>
              </div>

              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Button
                  variant="outline"
                  className="flex items-center gap-2"
                  onClick={handleViewPreview}
                >
                  <ExternalLink className="h-4 w-4" />
                  Visualizar como fica
                </Button>
                <Button
                  variant="default"
                  className="flex items-center gap-2"
                  onClick={handleCopyLink}
                >
                  <Copy className="h-4 w-4" />
                  {copied ? "Link copiado!" : "Copiar link"}
                </Button>
              </div>
            </div>

            <div className="mt-8 pt-6 border-t">
              <h4 className="font-medium mb-2">O que acontece agora?</h4>
              <ol className="space-y-2 text-sm text-muted-foreground list-decimal pl-5">
                <li>
                  O destinatário receberá o link e preencherá os dados
                  solicitados
                </li>
                <li>
                  Após o preenchimento, o contrato será gerado com os dados
                  inseridos
                </li>
                <li>
                  Você receberá uma notificação quando o preenchimento for
                  concluído
                </li>
                <li>
                  Você poderá revisar o contrato e enviá-lo para assinatura
                </li>
              </ol>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Action buttons */}
      <div className="flex justify-between mt-4">
        <Button variant="outline" onClick={onBack}>
          Voltar para Revisão de Campos
        </Button>
        <Button onClick={onFinish}>Concluir</Button>
      </div>
    </div>
  );
};

export default PublicLinkDisplay;
